ECONOMIC_SECTORS_MAP = {
    'nezistené': 'undefined',
    'Ostatné činnosti': 'other activities',
    'Poľnohospodárstvo, lesníctvo a rybolov': 'primary',
    'Ťažba a dobývanie': 'primary',
    'Stavebníctvo': 'secondary',
    'Priemyselná výroba': 'secondary',
    'Veľkoobchod a maloobchod; oprava motorových vozidiel a motocyklov': 'tertiary',
    'Doprava a skladovanie': 'tertiary',
    'Ubytovacie a stravovacie služby': 'tertiary',
    'Informácie a komunikácia': 'tertiary',
    'Činnosti v oblasti nehnuteľností': 'tertiary',
    'Odborné, vedecké a technické činnosti': 'tertiary',
    'Administratívne a podporné služby': 'tertiary',
    'Vzdelávanie': 'tertiary',
    'Umenie, zábava a rekreácia': 'tertiary',
    'Činnosti extrateritoriálnych organizácií a združení': 'tertiary',
    'Zdravotníctvo a sociálna pomoc': 'tertiary',
    'Dodávka elektriny, plynu, pary a studeného vzduchu': 'tertiary',
    'Finančné a poisťovacie činnosti': 'tertiary',
    'Dodávka vody; čistenie a odvod odpadových vôd, odpady a služby odstraňovania odpadov': 'tertiary',
    'Verejná správa a obrana; povinné sociálne zabezpečenie': 'tertiary',
    'Činnosti domácností ako zamestnávateľov; nediferencované činnosti v domácnostiach produkujúce tovary a služby na vlastné použitie': 'tertiary'
}