REQURED_EDUCATION_MAP = {
    "Pracovníci v osobných službách": "without",
    "Odborní pracovníci v oblasti práva, sociálnych vecí a kultúry a podobní pracovníci": "higher",
    "Administratívni pracovníci v zákazníckych službách": "secondary",
    "Riadiaci pracovníci (manažéri) vo výrobe a v špecializovaných službách": "higher",
    "Špecialisti v oblasti práva, sociálnych vecí a kultúry": "higher",
    "Administratívni pracovníci na záznam číselných a skladových údajov": "secondary",
    "Predavači": "without",
    "Pracovníci pri likvidácii odpadu a ostatní nekvalifikovaní pracovníci": "without",
    "Riadiaci pracovníci (manažéri) v hotelových, reštauračných, obchodných a v ostatných službách": "higher",
    "Špecialisti v oblasti vedy a techniky": "higher",
    "Špecialisti v oblasti informačných a komunikačných technológií": "higher",
    "Kvalifikovaní robotníci v hutníctve, strojárstve a podobní robotníci": "vocational",
    "Montážni robotníci": "vocational",
    "Vodiči a obsluha pojazdných strojných zariadení": "vocational",
    "Technici v oblasti informačných a komunikačných technológií": "higher",
    "Elektrikári a elektronici": "vocational",
    "Riadiaci pracovníci (manažéri) administratívnych, podporných a obchodných činností": "higher",
    "Špecialisti administratívnych, podporných a obchodných činností": "higher",
    "Technici a odborní pracovníci v oblasti vedy a techniky": "higher",
    "Odborní pracovníci v zdravotníctve": "higher",
    "Odborní pracovníci administratívnych, podporných a obchodných činností": "higher",
    "Pracovníci v oblasti osobnej starostlivosti": "vocational",
    "Spracovatelia a výrobcovia potravinárskych výrobkov, výrobkov z dreva a odevov": "vocational",
    "Operátori stacionárnych strojov a zariadení": "vocational",
    "Všeobecní administratívni pracovníci a zapisovatelia": "secondary",
    "Pracovníci verejnej ochrany a bezpečnostných služieb": "vocational",
    "Učitelia a odborní pedagogickí pracovníci": "higher",
    "Ostatní pomocní administratívni pracovníci": "secondary",
    "Špecialisti v zdravotníctve": "higher",
    "Pomocní pracovníci v ťažbe, stavebníctve, výrobe a doprave": "without",
    "Pomocní pracovníci pri príprave jedla": "without",
    "Kvalifikovaní pracovníci v poľnohospodárstve (trhovo orientovaní)": "vocational",
    "Zákonodarcovia, ústavní činitelia, vysokí štátni úradníci a najvyšší predstavitelia podnikov a organizácií": "higher",
    "Umeleckí a ruční remeselníci a tlačiari": "vocational",
    "Ostatné ozbrojené sily": "inapplicable",
    "Dôstojníci ozbrojených síl": "inapplicable",
    "Upratovači a pomocníci": "without",
    "Kvalifikovaní stavební robotníci a remeselníci okrem elektrikárov": "vocational",
    "Pomocní pracovníci v poľnohospodárstve, lesníctve a rybárstve": "without",
    "Poddôstojníci ozbrojených síl": "inapplicable",
    "Pouliční predavači a pomocní pracovníci v podobných službách": "without",
    "Kvalifikovaní pracovníci v lesníctve, rybárstve a poľovníctve (trhovo orientovaní)": "vocational",
    "Farmári, rybári, poľovníci a zberači úrody (samozásobovatelia)": "without",
}
